<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [11]:
data = [1,3.5,-12, 'olma']
array = np.array(data)
print(type(array[2]))


<class 'numpy.int64'>


in Numpy we can create arrays with elements of different types. however, numpy changes element types into one type for all array's elements. in the case above, 1st element of the array isn't integer but string becuse there is a string type element in the array. if you delete the string type element and check 1st element's type it is not integer again! it will be float, because there is a float type element in our array.

In [13]:
# Checking array demention

print(array.ndim)

1


In [15]:
# creating multidemetional arrays

myList = [[1,2,3,4,5],[6,7,8,9,10]]
myArray = np.array(myList)

print(myArray.ndim)

2


shape and size
shape for cheking dementions of array and size for element count

In [20]:
print(myArray.shape) # output (rows,columns)
print(myArray.size) # elements count

(2, 5)
10


Zeroes and Ones

In [22]:
arr4 = np.zeros((2,3)) # creating 2x3 array or matrix filled with 0
arr5 = np. ones((3,4)) # 4x5 array or matrix filled with 1
print(arr4)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.arange() = range()

In [24]:
arr6 = np.arange(4,20,2)
print(arr6)

[ 4  6  8 10 12 14 16 18]


random arrays

In [25]:
arr8 = np.random.rand(2,4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) taxminiy qiymatlardan tashkil topgan
arr8

array([[0.16758948, 0.64312716, 0.47180615, 0.14661153],
       [0.20413052, 0.35917021, 0.58292759, 0.63096755]])

In [26]:
arr9 = np.random.randint(5, size=(2, 4)) # (2, 4) o'lchamli va max qiymati 5 gacha bo'lgan int sonlar
arr9

array([[3, 4, 1, 2],
       [2, 2, 0, 2]])

In [27]:
arr10 = np.random.randn(2, 4) # (2, 4) o'lchamli --> elementlari (Normal dist)
arr10

array([[ 0.63308179,  1.03269093, -0.42881545,  2.89258541],
       [-0.21947486, -0.68089374,  0.52286037,  0.17777253]])