<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x  = np.random.randint(1,6,size=(2,3))

In [ ]:
x

array([[4, 2, 2],
       [3, 4, 5]])

In [ ]:
y = np.random.randint(5,10,size=(2,3))

In [ ]:
y

array([[6, 6, 9],
       [5, 9, 7]])

In [ ]:
x+y # each element of the x matrix be added to corresponding element of the y matrix

array([[10,  8, 11],
       [ 8, 13, 12]])

In [ ]:
y - x

array([[2, 4, 7],
       [2, 5, 2]])

In [ ]:
# scalar multiplication e.t. multiplication of a number to a matrix/array
5*x

array([[20, 10, 10],
       [15, 20, 25]])

Matrix multiplication

In [ ]:
a = np.random.randint(2,5,size=(2,3))
a

array([[3, 4, 3],
       [2, 3, 4]])

In [ ]:
b = np.random.randint(5,9,size=(3,2))
b

array([[5, 8],
       [6, 6],
       [8, 6]])

In [18]:
a.dot(b)

array([[63, 66],
       [60, 58]])

In [19]:
np.dot(a,b)

array([[63, 66],
       [60, 58]])

In [20]:
a@b

array([[63, 66],
       [60, 58]])

In [21]:
b@a

array([[31, 44, 47],
       [30, 42, 42],
       [36, 50, 48]])

In [ ]:
# Linear algebra
from numpy.linalg import inv