<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

In [2]:
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


In [3]:
print(np.show_config)

<function show at 0x7a4053e5dfc0>


#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
import random
randlist = random.sample(range(50),10)
randlist


[12, 39, 5, 32, 2, 46, 21, 8, 42, 14]

In [6]:
nparr = np.array(randlist)
nparr

array([12, 39,  5, 32,  2, 46, 21,  8, 42, 14])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [9]:
zrarr = np.zeros(shape=(9,9))

In [10]:
zrarr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [14]:
arr = np.random.randint(50,80,10)
arr

array([79, 55, 53, 52, 71, 66, 61, 69, 75, 57])

In [16]:
arr.size # the number of elements

10

In [17]:
arr.itemsize # number of bytes used to store a single element

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [20]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [23]:
arr12 = np.zeros(12)
arr12[5] = 1
arr12

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [24]:
np.arange(20,59)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [25]:
arr2 = np.arange(20,59)
arr2[::-1]

array([58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [27]:
arr3 = np.arange(12,21).reshape(3,3)
arr3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [28]:
arr4 = [3, 7, 0, 0, 9, 0]
np.nonzero(arr4)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [33]:
arr5 = np.random.random(size=(2,2,2))
arr5

array([[[0.10384734, 0.05532947],
        [0.2383848 , 0.82324207]],

       [[0.65026823, 0.53565344],
        [0.88198768, 0.58822361]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [34]:
arr6 =  np.random.random(size=(9,9))
arr6


array([[0.78228051, 0.65075647, 0.31515882, 0.88987807, 0.21768284,
        0.08285745, 0.0748438 , 0.88404354, 0.4932035 ],
       [0.45133837, 0.21909705, 0.6644021 , 0.57936819, 0.98307089,
        0.191718  , 0.78272219, 0.00483728, 0.62179629],
       [0.81190586, 0.86631698, 0.90180316, 0.84342949, 0.97638269,
        0.26029214, 0.95549241, 0.87035596, 0.56474858],
       [0.66611776, 0.77390541, 0.51313417, 0.72275211, 0.92253615,
        0.05765504, 0.90511734, 0.99093494, 0.44520549],
       [0.91445944, 0.92010754, 0.67716055, 0.89724118, 0.19094214,
        0.24561484, 0.28964602, 0.02528128, 0.12347444],
       [0.08756918, 0.79575174, 0.96521298, 0.93169768, 0.70506021,
        0.70933073, 0.4124893 , 0.32893046, 0.71432411],
       [0.90517371, 0.04626067, 0.39553487, 0.52360258, 0.78888273,
        0.23734995, 0.41756474, 0.59327322, 0.77782771],
       [0.09217664, 0.30780473, 0.60986857, 0.74517636, 0.07456159,
        0.98589733, 0.8229845 , 0.21086915, 0.15790025],


In [36]:
arr6.min()

0.004837275689593579

In [37]:
arr6.max()

0.9909349381495597

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [42]:
arr7 = np.random.random(size=(6,3))
arr8 = np.random.random(size=(3,4))


In [43]:
np.dot(arr7,arr8)

array([[1.07351406, 1.08294583, 1.53803714, 1.16853378],
       [0.6945542 , 0.71593222, 1.08209925, 0.8876003 ],
       [0.29014873, 0.64794073, 0.99696576, 0.71130665],
       [0.30942703, 0.27932407, 0.44481101, 0.40225337],
       [0.98072193, 1.22370794, 1.79239101, 1.33548304],
       [1.0386746 , 1.09396944, 1.59583278, 1.24143797]])

In [44]:
arr7@arr8

array([[1.07351406, 1.08294583, 1.53803714, 1.16853378],
       [0.6945542 , 0.71593222, 1.08209925, 0.8876003 ],
       [0.29014873, 0.64794073, 0.99696576, 0.71130665],
       [0.30942703, 0.27932407, 0.44481101, 0.40225337],
       [0.98072193, 1.22370794, 1.79239101, 1.33548304],
       [1.0386746 , 1.09396944, 1.59583278, 1.24143797]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [47]:
print(sum(range(5),-1))

9


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [50]:
arr10 = np.random.randint(10,50,5)
arr11 = np.random.randint(10,50,5)

In [52]:
arr10

array([12, 12, 12, 21, 16])

In [53]:
arr11

array([33, 10, 47, 26, 10])

In [54]:
arr10>arr11

array([False,  True, False, False,  True])

In [55]:
arr10<arr11

array([ True, False,  True,  True, False])

In [56]:
arr10>=arr11

array([False,  True, False, False,  True])

In [57]:
arr10<=arr11

array([ True, False,  True,  True, False])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

Let's go through each of these NumPy expressions:

1. `np.array(0) / np.array(0)`:
   - This will result in a `nan` (not-a-number). When you divide zero by zero, the result is undefined, which is represented as `nan` in NumPy.

2. `np.array(0) // np.array(0)`:
   - This will also result in a `nan`. The floor division operator `//` behaves similarly to regular division when dividing zero by zero, resulting in `nan`.

3. `np.array([np.nan]).astype(int).astype(float)`:
   - This expression converts a NumPy array containing a `nan` as a float to an integer, and then back to a float.
   - The first `.astype(int)` conversion will result in `array([0])`. Converting `nan` to an integer results in `0`.
   - The second `.astype(float)` conversion will then result in `array([0.])`. The integer `0` is converted back to a float, resulting in `0.0`.

Keep in mind that when performing operations with `nan`, the result will often be `nan`, and when converting `nan` to an integer, it becomes `0`. The behavior is designed to handle undefined or missing values in a predictable way.

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [67]:
arr14 = np.random.random(5)*10
arr14 = [int(i) for i in arr14]
arr14

[2, 9, 4, 5, 4]

In [73]:
arr15 = np.random.random(5)*10
arr15 = [int(i) for i in arr15]
arr15

[6, 1, 5, 3, 2]

In [74]:
np.intersect1d(arr14,arr15)

array([2, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [76]:
arr16 = np.random.random(5)*10
arr16

array([8.6324878 , 2.67153964, 6.64401146, 5.40253237, 4.80314106])

In [80]:
# %
result = arr16%1
result

array([0.6324878 , 0.67153964, 0.64401146, 0.40253237, 0.80314106])

In [87]:
rsl = np.floor(arr16)
rsl

array([8., 2., 6., 5., 4.])

In [89]:
rsl = arr16.astype(int)
rsl

array([8, 2, 6, 5, 4])

In [91]:
rsl = np.trunc(arr16)
rsl

array([8., 2., 6., 5., 4.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [95]:
arr17 = np.arange(9).reshape(3,3)
arr17

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [97]:
arr18 = np.random.random(10)*10
arr18.sort()
arr18

array([0.68401137, 0.84821692, 1.42435775, 3.38590609, 4.09319492,
       5.3721772 , 5.85745435, 6.27814253, 8.08425133, 8.55288468])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [98]:
A = np.random.random(5)
B= np.random.random(5)

array([0.89918589, 0.72548837, 0.21150861, 0.63968979, 0.26682513])

In [99]:
A

array([0.21268402, 0.74634303, 0.9819156 , 0.65452321, 0.73635542])

In [100]:
B

array([0.89918589, 0.72548837, 0.21150861, 0.63968979, 0.26682513])

In [101]:
np.allclose(A,B)

False

In [102]:
np.array_equal(A,B)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [105]:
arr20 = np.random.randint(0,10, (6,3))
arr20

array([[3, 9, 8],
       [8, 6, 0],
       [3, 9, 3],
       [2, 1, 3],
       [0, 1, 4],
       [9, 8, 1]])

In [24]:
arr21 = np.random.randint(0,10, (3,4))
arr21

array([[7, 5, 9, 6],
       [9, 8, 4, 2],
       [5, 9, 0, 9]])

In [108]:
np.dot(arr20,arr21)

array([[129,  62,  81,  35],
       [108,  44,  62,  18],
       [ 99,  42,  66,  30],
       [ 42,  22,  22,   6],
       [ 30,  18,  17,   7],
       [135,  56,  79,  25]])

In [109]:
np.ones(arr20,arr21)

TypeError: ignored

In [110]:
arr20@arr21

array([[129,  62,  81,  35],
       [108,  44,  62,  18],
       [ 99,  42,  66,  30],
       [ 42,  22,  22,   6],
       [ 30,  18,  17,   7],
       [135,  56,  79,  25]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [23]:
arr22 = np.random.random(10)
arr22*10

array([8.13489568, 0.07125607, 3.74378151, 9.21625798, 5.40573688,
       6.22316248, 2.80732067, 1.43994948, 3.48539578, 9.24548593])

In [122]:
max_el = np.argmax(arr22)
arr22[max_el] = 0
arr22

array([0.64655006, 0.34116441, 0.44380435, 0.        , 0.30126503,
       0.19741729, 0.64156681, 0.71511725, 0.56191463, 0.37339524])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [127]:
np.datetime64('2002-12-02')

numpy.datetime64('2002-12-02')

In [128]:
np.timedelta64()

numpy.timedelta64(0)

In [4]:
today = np.datetime64('today')
today

numpy.datetime64('2023-10-14')

In [8]:
yesterday = today - np.timedelta64(1,'D')
yesterday

numpy.datetime64('2023-10-13')

In [9]:
tomorrow = today + np.timedelta64(1,'D')
tomorrow

numpy.datetime64('2023-10-15')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [5]:
import numpy as np
sanalar = np.arange('2016-01','2016-02',dtype='datetime64[D]')
sanalar

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

In [8]:
print(f"My father was born in {sanalar[19]}")

My father was born in 2016-01-20


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [11]:
3.14-3.14%1

3.0

In [15]:
arr23 = -10*np.random.random(5)
arr23

array([-8.66767269, -9.68846952, -9.18815605, -2.7125084 , -2.05756962])

In [18]:
arr23-arr23%1

array([ -9., -10., -10.,  -3.,  -3.])

In [19]:
np.floor(arr23)

array([ -9., -10., -10.,  -3.,  -3.])

In [21]:
arr23.astype(int)

array([-8, -9, -9, -2, -2])

In [22]:
np.trunc(arr23)

array([-8., -9., -9., -2., -2.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [31]:
np.sum(arr23)

-32.314376276754395

In [29]:
arr24 = 10*np.random.random(5)
arr24

array([7.32733218, 9.60275015, 8.50183319, 9.58292649, 7.5522166 ])

In [30]:
arr25 = 10*np.random.random(5)
arr25

array([3.22123882, 4.98150925, 0.89275975, 9.22586918, 5.43328128])

In [32]:
np.sum(arr23)

-32.314376276754395

In [33]:
np.add.reduce(arr23)

-32.314376276754395

In [34]:
import numpy as np
import timeit

# Create a large NumPy array for testing
arr = np.random.rand(1000000)

# Define a function to compare np.sum and np.add.reduce
def sum_method():
    return np.sum(arr)

def reduce_method():
    return np.add.reduce(arr)

# Measure the time taken by np.sum
time_sum = timeit.timeit(sum_method, number=100)

# Measure the time taken by np.add.reduce
time_reduce = timeit.timeit(reduce_method, number=100)

print("Time taken by np.sum:", time_sum)
print("Time taken by np.add.reduce:", time_reduce)


Time taken by np.sum: 0.06392816800007495
Time taken by np.add.reduce: 0.06357495000020208


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [37]:
arr25 = np.arange(1,6)
arr26 = np.array([])
for i in arr25:
  arr26 = np.append(arr26,i)
  for i in range(3):
    arr26 = np.append(arr26, 0)
print(arr26)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [38]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

# Create a sample array
arr = np.array([1, 2, 3, 4, 5, 6])

# Use as_strided to create a new view of the array with a different shape and strides
strided_arr = as_strided(arr, shape=(4, 2), strides=(4, 4))

# Print the strided array
print(strided_arr)


[[          1  8589934592]
 [ 8589934592           2]
 [          2 12884901888]
 [12884901888           3]]


In [39]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Yaratilayotgan b massivning shape'i
new_shape = (a.shape[0] - 3 + 1, 4)

# b massivni yaratish
b = np.lib.stride_tricks.as_strided(a, shape=new_shape, strides=(a.itemsize, a.itemsize))

print(b)


[[              1               2               3               4]
 [              2               3               4               5]
 [              3               4               5               6]
 [              4               5               6               7]
 [              5               6               7               8]
 [              6               7               8               9]
 [              7               8               9              10]
 [              8               9              10              11]
 [              9              10              11              12]
 [             10              11              12              13]
 [             11              12              13              14]
 [             12              13              14 138154038690352]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [52]:
arr23 = -arr23.astype(int)
arr23

array([ 9, 10, 10,  3,  3])

In [50]:
arr24 = arr24.astype(int)
arr24

array([7, 9, 8, 9, 7])

In [53]:
np.bincount(arr23)

array([0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2])

In [54]:
np.bincount([1,2,3])

array([0, 1, 1, 1])

In [56]:
np.bincount([1,2,3,1,2,2,3,3,3])

array([0, 2, 3, 4])

In [58]:
arr28 = np.array([1,2,3,4,5])
arr29 = np.array([1,2,2,3,3,3])

In [59]:
np.in1d(arr28,arr29)

array([ True,  True,  True, False, False])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`