<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/np_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('arr-data',arr)

In [5]:
arr2 = np.load('arr-data.npy')

In [6]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savetxt('arr-txt-data',arr)

In [14]:
arrtxt2 = np.loadtxt('arr-txt-data')

In [15]:
arrtxt2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
arr2 = np.arange(20)

In [17]:
arrays = np.savez('arrays', a = arr, b = arr2)

In [18]:
arrays = np.load("arrays.npz")

In [19]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arrays


In [23]:
np.savez_compressed('arrs-compressed.npz',a=arr,b = arr2)

In [24]:
arr_compr = np.load('arrs-compressed.npz')

In [25]:
arr_compr['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])