<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/np_math_stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
from numpy.lib.shape_base import array_split
arr = np.random.randn(5,4)
arr

array([[ 0.29338908, -0.36753354, -0.69161527,  0.21442292],
       [-2.96927574,  0.34633058,  0.29613119,  1.24105001],
       [-0.1625932 ,  1.88339145, -2.19374045,  0.67427031],
       [ 2.28893092, -1.63380697,  0.73602869, -0.39135728],
       [-0.39707176, -1.93205187,  0.93018529,  0.57430014]])

In [12]:
# sum method
arr.sum()



-1.260615484517022

In [13]:
np.sum(arr)

-1.260615484517022

In [14]:
arr1 = np.random.randint(-5,5,size=(5,4))

In [15]:
arr1

array([[-3, -5, -3,  1],
       [-2, -4,  3, -2],
       [ 4,  1,  4,  4],
       [ 4,  2, -2, -4],
       [-3, -2,  1, -4]])

In [17]:
arr1.sum(axis=0) # sum of colums

array([ 0, -8,  3, -5])

In [18]:
arr1.sum(axis=1) # sum of rows

array([-10,  -5,  13,   0,  -8])

In [20]:
# mean method

data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [21]:
mean = np.sum(data)/len(data)
mean

2.0

In [22]:
np.mean(data)

2.0

In [23]:
data.mean()

2.0

In [24]:
np.mean(arr1)

-0.5

In [25]:
arr1

array([[-3, -5, -3,  1],
       [-2, -4,  3, -2],
       [ 4,  1,  4,  4],
       [ 4,  2, -2, -4],
       [-3, -2,  1, -4]])

In [27]:
np.mean(arr1, axis=1)

array([-2.5 , -1.25,  3.25,  0.  , -2.  ])

In [30]:
arr1.mean(axis=0)

array([ 0. , -1.6,  0.6, -1. ])

In [31]:
# cumsum - cumilitive sum

data


array([0, 1, 2, 3, 4])

In [32]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [33]:
data[1:].cumprod()

array([ 1,  2,  6, 24])

Tartiblash - Sorting

In [37]:
arr = np.random.rand(4)
arr

array([0.98288127, 0.93001189, 0.80747443, 0.41640563])

In [38]:
sorted_arr = np.sort(arr)
sorted_arr

array([0.41640563, 0.80747443, 0.93001189, 0.98288127])

In [46]:
arr.sort()
arr


array([0.41640563, 0.80747443, 0.93001189, 0.98288127])

In [49]:
# decending order

revArr = np.sort(-arr)
revArr

array([-0.98288127, -0.93001189, -0.80747443, -0.41640563])

In [50]:
revArr = -np.sort(arr)
revArr

array([-0.41640563, -0.80747443, -0.93001189, -0.98288127])

In [53]:
# Right way

revArr = -np.sort(-arr)
revArr

array([0.98288127, 0.93001189, 0.80747443, 0.41640563])

In [54]:
# 2D array

array2d = np.random.randn(2,4)
array2d

array([[ 1.20420529, -0.33742541, -1.09697277,  0.02620984],
       [ 0.08565363, -0.46410429, -0.3883953 ,  0.02877614]])

In [56]:
array2d.ndim


2

In [57]:
from typing_extensions import clear_overloads
col_srt = np.sort(array2d,axis=0) # arr2d sorted by column
clear_overloads_srt
# axis 0 -> Column

array([[ 0.08565363, -0.46410429, -1.09697277,  0.02620984],
       [ 1.20420529, -0.33742541, -0.3883953 ,  0.02877614]])

In [58]:
# axis 1 --> row

row_srt = np.sort(array2d,axis = 1)
row_srt


array([[-1.09697277, -0.33742541,  0.02620984,  1.20420529],
       [-0.46410429, -0.3883953 ,  0.02877614,  0.08565363]])