<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/NumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In numpy array elements types are similar to c and c++.

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4],dtype=np.int8)
arr1.dtype


dtype('int8')

In [ ]:
float_arr = arr1.astype(np.float64)
float_arr

array([1., 2., 3., 4.])

If you change sliced part of the array, this change effects the original array too.

In [ ]:
arr = np.arange(10,100,10)
sliced_arr = arr[3:5]
sliced_arr[:] = 0 # assigning 0 to all elemets of the array
print("Sliced array: ",sliced_arr)
print("Original array",arr)

Sliced array:  [0 0]
Original array [10 20 30  0  0 60 70 80 90]


In order to avoid above metntioned issue, we use .copy() method

In [ ]:
arr1 = np.arange(10,100,10)
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0
print("Sliced array: ",sliced_arr1)
print("Original array",arr1) # now, the original array has not been modified

Sliced array:  [0 0]
Original array [10 20 30 40 50 60 70 80 90]


Working with 2 DEMENTIONAL arrays

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3[0,0])

1


Slicing

In [ ]:
print(arr3[2,1:3]) # arr3[row-number,slicing-element-indexes]
print('arr3[:2,1:]: \n',arr3[:2,1:])
print('Only 3rd row',arr3[2]) # arr[2,:], arr[2:,:]

[8 9]
arr3[:2,1:]: 
 [[2 3]
 [5 6]]
Only 3rd row [7 8 9]


In [ ]:
arr3[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr3[1,:2]

array([4, 5])

Indexing 3d arrays is similar to 2d array indexing. Just we should devide up 3d arrays into 2d arrays.

Boolean indexing

In [ ]:
names = np.array(['Hasan','Husan','Husaying','Abdulloh','Shukrulloh','Nasrulloh', 'Hasan'])
names

array(['Hasan', 'Husan', 'Husaying', 'Abdulloh', 'Shukrulloh',
       'Nasrulloh', 'Hasan'], dtype='<U10')

In [ ]:
data = np.random.randn(7,4)
data

array([[ 0.90756669, -0.02943653, -1.01460319, -1.16862477],
       [ 0.59149036,  1.27390202,  0.36634006,  0.41566464],
       [-0.98743305, -0.87207505,  0.60058259,  1.41984452],
       [-1.53024442, -1.14649562,  0.26721603,  2.9615051 ],
       [-0.64777695,  1.15926332, -2.1333205 , -0.58838041],
       [ 0.27659249,  0.55529502, -1.16093462, -0.20721522],
       [ 0.82382319,  1.48271346, -0.76296736, -0.39847085]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False, False, False,  True])

In [ ]:
data[names == 'Abdulloh']

array([[-1.53024442, -1.14649562,  0.26721603,  2.9615051 ]])

In [ ]:
surnames = np.array(['Toshev','Norev','Aliev','Valiyev','Soliyev','Avazov','Komiljonov'])


In [ ]:
surnames == 'Toshev'


array([ True, False, False, False, False, False, False])

In [ ]:
surnames[names == 'Abdulloh']

array(['Valiyev'], dtype='<U10')

In [ ]:
names[surnames == 'Norev']

array(['Husan'], dtype='<U10')

In [ ]:
data[names != 'Hasan']


array([[ 0.59149036,  1.27390202,  0.36634006,  0.41566464],
       [-0.98743305, -0.87207505,  0.60058259,  1.41984452],
       [-1.53024442, -1.14649562,  0.26721603,  2.9615051 ],
       [-0.64777695,  1.15926332, -2.1333205 , -0.58838041],
       [ 0.27659249,  0.55529502, -1.16093462, -0.20721522]])

Transpose and Swap

In [ ]:
import numpy as np

A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

A*A^T

In [ ]:
A@A.T

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [ ]:
np.dot(A,A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])