<a href="https://colab.research.google.com/github/KamronbekSolih/mohirdev/blob/main/universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr) # returns root squared of arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.log(arr)

<ipython-input-8-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
arr1 = 10*np.random.randn(6)
arr1

array([  2.01303764,  -3.78905947, -11.53180354,   3.25155044,
        13.88823288,  13.9343096 ])

In [14]:
qoldiq, butun = np.modf(arr1)

In [15]:
qoldiq

array([ 0.01303764, -0.78905947, -0.53180354,  0.25155044,  0.88823288,
        0.9343096 ])

In [16]:
butun

array([  2.,  -3., -11.,   3.,  13.,  13.])

In [17]:
np.sign(arr1)

array([ 1., -1., -1.,  1.,  1.,  1.])

In [18]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [19]:
arr1[1] = None


In [20]:
np.isnan(arr1)

array([False,  True, False, False, False, False])

In [24]:
if True in np.isnan(arr1):
  print("Danger!")

Danger!


Binary functions

In [25]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [26]:
arr2


array([ 0.84682852, -1.11436901, -0.73056905, -0.89018014,  0.03100417,
        0.45717667])

In [27]:
arr3

array([-0.41045452, -1.01363956,  1.21619218,  0.37399545,  1.10462851,
       -1.01097659])

In [28]:
np.add(arr2,arr3)

array([ 0.43637399, -2.12800856,  0.48562313, -0.51618469,  1.13563268,
       -0.55379992])

In [29]:
arr2+arr3

array([ 0.43637399, -2.12800856,  0.48562313, -0.51618469,  1.13563268,
       -0.55379992])

In [30]:
np.multiply(arr2,arr3)

array([-0.3475846 ,  1.1295685 , -0.88851237, -0.33292333,  0.03424809,
       -0.46219491])

In [31]:
arr2*arr3

array([-0.3475846 ,  1.1295685 , -0.88851237, -0.33292333,  0.03424809,
       -0.46219491])

In [32]:
np.maximum(arr2,arr3) # compares 2 elements of the arrays and returns bigger one

array([ 0.84682852, -1.01363956,  1.21619218,  0.37399545,  1.10462851,
        0.45717667])